export const salesData = [
  {
    month: "January",
    total_earnings: 23300.0,
    date: "23rd April",
    "Data Science for Beginners": 2500.0,
    "Software Engineering Fundamentals": 3000.0,
    "Creative Writing Masterclass": 1500.0,
    "Marketing Strategies for Startups": 600.0,
    "Web Development Bootcamp": 4300.0,
    "Public Speaking Essentials": 1200.0,
    "Graphic Design for Everyone": 2500.0,
    "Financial Management for Freelancers": 2800.0,
  },

  {
    month: "February",
    total_earnings: 233,
    date: "23rd April",
    "Data Science for Beginners": 250.0,
    "Software Engineering Fundamentals": 3000.0,
    "Creative Writing Masterclass": 100.0,
    "Marketing Strategies for Startups": 500.0,
    "Web Development Bootcamp": 300.0,
    "Public Speaking Essentials": 120.0,
    "Graphic Design for Everyone": 2500.0,
    "Financial Management for Freelancers": 2800.0,
  },
  {
    month: "March",
    total_earnings: 2330.0,
    date: "23rd April",
    "Data Science for Beginners": 2500.0,
    "Software Engineering Fundamentals": 300.0,
    "Creative Writing Masterclass": 1500.0,
    "Marketing Strategies for Startups": 2500.0,
    "Web Development Bootcamp": 4300.0,
    "Public Speaking Essentials": 1200.0,
    "Graphic Design for Everyone": 2500.0,
    "Financial Management for Freelancers": 2800.0,
  },
  {
    month: "April",
    total_earnings: 23300.0,
    date: "23rd April",
    "Data Science for Beginners": 2500.0,
    "Software Engineering Fundamentals": 3000.0,
    "Creative Writing Masterclass": 1500.0,
    "Marketing Strategies for Startups": 500.0,
    "Web Development Bootcamp": 4300.0,
    "Public Speaking Essentials": 1200.0,
    "Graphic Design for Everyone": 2500.0,
    "Financial Management for Freelancers": 2800.0,
  },
  {
    month: "May",
    total_earnings: 23300.0,
    date: "23rd April",
    "Data Science for Beginners": 2500.0,
    "Software Engineering Fundamentals": 3000.0,
    "Creative Writing Masterclass": 1500.0,
    "Marketing Strategies for Startups": 500.0,
    "Web Development Bootcamp": 4300.0,
    "Public Speaking Essentials": 1200.0,
    "Graphic Design for Everyone": 2500.0,
    "Financial Management for Freelancers": 2800.0,
  },
  {
    month: "June",
    total_earnings: 23300.0,
    date: "23rd April",
    "Data Science for Beginners": 2500.0,
    "Software Engineering Fundamentals": 3000.0,
    "Creative Writing Masterclass": 1500.0,
    "Marketing Strategies for Startups":500.0,
    "Web Development Bootcamp": 4300.0,
    "Public Speaking Essentials": 1200.0,
    "Graphic Design for Everyone": 2500.0,
    "Financial Management for Freelancers": 2800.0,
  },

//   {
//     month: "February",
//     total_earnings: 23300.0,
//     courses: [
//       {
//         name: "Data Science for Beginners",
//         earning: 2500.0,
//         "hot dogColor": "hsl(201, 70%, 50%)",
//       },
//       {
//         name: "Software Engineering Fundamentals",
//         earning: 3000.0,
//         burgerColor: "hsl(52, 70%, 50%)",
//       },
//       {
//         name: "Creative Writing Masterclass",
//         earning: 1500.0,
//       },
//       {
//         name: "Marketing Strategies for Startups",
//         earning: 5500.0,
//       },
//       {
//         name: "Web Development Bootcamp",
//         earning: 4300.0,
//       },
//       {
//         name: "Public Speaking Essentials",
//         earning: 1200.0,
//       },
//       {
//         name: "Graphic Design for Everyone",
//         earning: 2500.0,
//       },
//       {
//         name: "Financial Management for Freelancers",
//         earning: 2800.0,
//       },
//     ],
//   },
];
